"""empty message

Revision ID: 4ac23cd0c97d
Revises: 
Create Date: 2021-07-24 12:06:44.105084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac23cd0c97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actors')
    op.drop_table('actor')
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('movie_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='movie_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('actor',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('actor_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='actor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('movie_actors',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], name='movie_actors_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='movie_actors_movie_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id', name='movie_actors_pkey')
    )
    # ### end Alembic commands ###
